# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: phongdev01
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: serverless-hdw
service: hdw-nestjs-serverless

useDotenv: true

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  environment:
    MONGODB_URI: ${env:MONGODB_URI}

functions:
  main:
    handler: dist/serverless.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
package:
  exclude:
    - node_modules/**
    - venv/**